// Single source of truth for the marketing photography served from
// public/images/marketing-images/.
//
// The files here are generated by `npm run images` from the originals in
// assets/images-src/ (see scripts/optimize-images.mjs). They were previously
// shipped as ~2 MB PNGs; as WebP at three widths they are ~90% smaller, and the
// browser downloads only the one variant it needs.
//
// Spread an entry straight onto an <img> to get src, srcSet and the real
// intrinsic dimensions in one go:
//
//   <img {...MARKETING_IMAGES.livingRoomAssembly} sizes="..." alt="..." />
//
// Passing width/height matters as much as the file size: the browser uses them
// to reserve space before the image loads, which is what keeps Cumulative
// Layout Shift at zero.

const BASE_PATH = '/images/marketing-images';

export interface MarketingImage {
  /** Full-size variant. Also what the lightbox opens. */
  src: string;
  /** 640w / 960w / full-size variants for the browser to choose between. */
  srcSet: string;
  /** Intrinsic dimensions of `src`, for aspect-ratio reservation. */
  width: number;
  height: number;
}

function variant(name: string, width: number, height: number): MarketingImage {
  return {
    src: `${BASE_PATH}/${name}.webp`,
    srcSet:
      `${BASE_PATH}/${name}-640.webp 640w, ` +
      `${BASE_PATH}/${name}-960.webp 960w, ` +
      `${BASE_PATH}/${name}.webp ${width}w`,
    width,
    height,
  };
}

export const MARKETING_IMAGES = {
  livingRoomAssembly: variant('Boxed2Built_Living_Room_Assembly', 1254, 1254),
  bedroomAssembly: variant('Boxed2Built_Bedroom_Assembly', 1254, 1254),
  nurseryAssembly: variant('Boxed2Built_Nursery_Assembly', 1254, 1254),
  garageAssembly: variant('Boxed2Built_Garage_Assembly', 1254, 1254),
  outdoorLiving: variant('Boxed2Built_Outdoor_Living', 1254, 1254),
  skipTheBuild: variant('Boxed2Built_Skip_The_Build_Enjoy_Moments', 1254, 1254),
  timeForWhatMatters: variant('Boxed2Built_Time_For_What_Matters_Most', 1254, 1254),
  founderPortrait: variant('nicholas-davidson-founder-portrait-spring-hill', 1254, 1710),
} as const satisfies Record<string, MarketingImage>;

export type MarketingImageKey = keyof typeof MARKETING_IMAGES;

/**
 * Which marketing images appear on which page, used to generate
 * public/sitemap-images.xml (see scripts/generate-sitemap.mjs).
 *
 * The previous image sitemap was hand-written and had rotted completely: every
 * local image it listed had been deleted and returned a 404, and the only
 * working entries pointed at Pexels stock photography that Boxed2Built does
 * not own and should never have been submitting as its own. Deriving the
 * sitemap from this mapping means it can only ever list images that exist.
 *
 * Keep an entry here only while the page actually renders that image.
 */
export const PAGE_IMAGES: ReadonlyArray<{
  /** Site-relative page path. */
  path: string;
  images: ReadonlyArray<{ key: MarketingImageKey; title: string; caption: string }>;
}> = [
  {
    path: '/',
    images: [
      {
        key: 'livingRoomAssembly',
        title: 'Living room furniture assembly in Spring Hill, TN',
        caption:
          'Boxed2Built assembling living room furniture for a family in Spring Hill, Tennessee.',
      },
      {
        key: 'skipTheBuild',
        title: 'Skip the flat-pack build — Boxed2Built furniture assembly',
        caption:
          'Professional flat-pack furniture assembly so Middle Tennessee families can enjoy the finished room instead of the instructions.',
      },
    ],
  },
  {
    path: '/services',
    images: [
      {
        key: 'garageAssembly',
        title: 'Garage storage and shelving assembly in Spring Hill, TN',
        caption:
          'Garage shelving and storage installation anchored into framing by Boxed2Built.',
      },
      {
        key: 'outdoorLiving',
        title: 'Patio and outdoor furniture assembly in Middle Tennessee',
        caption:
          'Outdoor and patio furniture assembly for homes across Williamson and Maury counties.',
      },
    ],
  },
  {
    path: '/services/furniture-assembly',
    images: [
      {
        key: 'bedroomAssembly',
        title: 'Bedroom furniture assembly — bed frame, dresser and nightstand',
        caption:
          'Bed frame, dresser and nightstand assembled and anchored by Boxed2Built in Spring Hill, TN.',
      },
      {
        key: 'skipTheBuild',
        title: 'Professional flat-pack furniture assembly service',
        caption:
          'IKEA, Wayfair, Target and Walmart furniture assembled, placed and cleaned up.',
      },
    ],
  },
  {
    path: '/about',
    images: [
      {
        key: 'founderPortrait',
        title: 'Nicholas Davidson, founder of Boxed2Built',
        caption:
          'Nicholas Davidson, owner and founder of Boxed2Built furniture assembly in Spring Hill, Tennessee.',
      },
      {
        key: 'timeForWhatMatters',
        title: 'Time for what matters most — Boxed2Built',
        caption:
          'Families spend time together while Boxed2Built handles the furniture assembly.',
      },
      {
        key: 'nurseryAssembly',
        title: 'Nursery furniture and crib assembly in Spring Hill, TN',
        caption:
          'Crib and nursery furniture assembled to manufacturer specification with anti-tip anchoring.',
      },
    ],
  },
];

/**
 * Default `sizes` for an image sitting in a roughly half-width content column.
 * Without this the browser assumes 100vw and pulls the full-size file even on
 * a phone, which defeats the point of shipping a 640w variant.
 */
export const HALF_COLUMN_SIZES = '(max-width: 1024px) 100vw, 45vw';
